site_name: Mercicor
site_author: 3Liz
site_description: Extension QGIS pour l'étude des récifs coralliens
site_url: http://packages.3liz.org/private/um3-mercicor/
copyright: '<span class="copyleft">&copy;</span> 3Liz'

docs_dir: docs
site_dir: build

nav:
    - Accueil: index.md
    - Guide utilisateur:
        - 'Index': 'user-guide/index.md'
        - 'Création du projet': 'user-guide/initialisation-projet.md'
        - 'Import des habitats': 'user-guide/import-donnees-habitats.md'
        - 'Préparation de la campagne': 'user-guide/preparation-observations.md'
        - 'Intégration de la campagne': 'user-guide/integration-campagne.md'
        - "Calcul de l'état écologique": 'user-guide/calcul-etat-ecologique.md'
        - 'Étude des scénarios': 'user-guide/etude-scenario.md'
        - 'Habitat pression état écologique': 'user-guide/habitat-pression-etat-ecologique.md'
        - 'Pertes': 'user-guide/pertes.md'
        - 'Installation': 'user-guide/installation.md'
    - 'Modèle de données': model/index.md
    - Traitements: processing/README.md
    - Changelog: changelog.md
    - Contribution: contributing.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: "#"
  - meta:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
  - pymdownx.magiclink:
  - pymdownx.tasklist:
  - pymdownx.snippets:
  - pymdownx.keys:
  - attr_list:
  - admonition:
  - pymdownx.details:

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

theme:
  name: material
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'fr'
  logo: media/icon.jpg
  favicon: media/icon.jpg
  palette:
    accent: deep-orange
    primary: green
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/3LIZ_news

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/3liz

    - icon: fontawesome/brands/github
      link: https://github.com/3liz/

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/3liz
